services:
  dev-mongodb-primary:
    image: docker.io/bitnami/mongodb:latest
    restart: always
    container_name: dev-mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=dev-mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=123456
      - MONGODB_REPLICA_SET_KEY=replicaset
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - 27017:27017

  dev-mongodb-secondary:
    image: docker.io/bitnami/mongodb:latest
    restart: always
    container_name: dev-mongodb-secondary
    depends_on:
      - dev-mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_ADVERTISED_HOSTNAME=dev-mongodb-secondary
      - MONGODB_INITIAL_PRIMARY_HOST=dev-mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_USER=root
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=123456
      - MONGODB_REPLICA_SET_KEY=replicaset
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
    ports:
      - 27027:27017

  dev-mongodb-arbiter:
    image: docker.io/bitnami/mongodb:latest
    restart: always
    container_name: dev-mongodb-arbiter
    depends_on:
      - dev-mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_ADVERTISED_HOSTNAME=dev-mongodb-arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=dev-mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_USER=root
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=123456
      - MONGODB_REPLICA_SET_KEY=replicaset
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
    ports:
      - 27037:27017

  redis:
    restart: always
    container_name: dev-single-redis
    image: docker.io/bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=123456
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  mongodb_master_data:
    driver: local
  redis_data:
    driver: local