import { Injectable, Logger } from '@nestjs/common'
import { isDev } from '@walnut/config/utils/env'
import { AppDayjs } from '@walnut/utils/dayjs'
import { isNil } from 'lodash'
import { ClientSession } from 'mongoose'
import { AppMonitorUserRepositoryService } from '@/modules/app/monitor/user/repo/user.repo.service'
import { SysDeviceRepositoryService } from '../../device/repo/device.repo.service'
import { SysDeviceSharedService } from '../../device/shared/device.shared.service'
import { SysUserDeviceRepositoryService } from '../repo/user_device.repo.service'

@Injectable()
export class SysUserDeviceSharedService {
  private readonly logger = new Logger(SysUserDeviceSharedService.name)

  constructor(
    private readonly userDeviceRepo: SysUserDeviceRepositoryService,
    private readonly appMonitorUserRepo: AppMonitorUserRepositoryService,

    private readonly deviceRepo: SysDeviceRepositoryService,
    private readonly deviceSharedService: SysDeviceSharedService,
  ) {}

  /**
   * @description get trusted devices of user
   */
  async getUserDeviceTrusted(
    userId: string,
    deviceId: string,
    dbSession?: ClientSession,
  ) {
    const device = await this.userDeviceRepo.findTrustedDevice(
      userId,
      deviceId,
      dbSession,
    )
    return this.userDeviceRepo.isTrustedAndValid(device)
  }

  /**
   * @description get all users by device id
   */
  async getAllUsersByDeviceId(deviceId: string) {
    const docs = await this.userDeviceRepo.findAllUserInCurrentDevice(deviceId)
    return docs
      .filter(i => isNil(i.populated_user?._id))
      .map(i => ({
        ...i.populated_user?.toObject(),
        lastActiveAt: i.lastActiveAt,
      }))
  }

  /**
   * @description bind device for user
   * @returns new document
   */
  async bindDeviceForUser(
    userId: string,
    deviceId: string,
    dbSession: ClientSession,
  ) {
    this.logger.log(`Bind device for user, userId: ${userId}, deviceId: ${deviceId}`)
    const deviceName = await this.deviceRepo.getDeviceNameByDeviceId(
      deviceId,
      dbSession,
    )

    this.logger.log(`Extracted Device name: ${deviceName}`)

    return this.userDeviceRepo.upsertDevice(
      userId,
      deviceId,
      deviceName,
      dbSession,
    )
  }

  /**
   * @description update trusted status for user device
   */
  async updateTrustedStatusForUserDevice(
    userId: string,
    deviceId: string,
    trusted: boolean,
    dbSession: ClientSession,
  ) {
    const trustedExpiredAt = trusted
      ? this.userDeviceRepo.getTrustedExpiredAt()
      : null

    return this.userDeviceRepo.updateTrustedStatus(
      userId,
      deviceId,
      trusted,
      trustedExpiredAt,
      dbSession,
    )
  }

  /**
   * @description update device active status for cron jobs
   * violently deactivate devices that have not been active for last 5 minutes
   * execute this method every 5 minutes
   */
  async updateDeviceActiveStatusForCronJob() {
    if (isDev) {
      return {
        matchedCount: 0,
        modifiedCount: 0,
        deletedCount: 0,
      }
    }

    const thresholdTime = AppDayjs().subtract(5, 'minute').toDate()
    const activeDevices = await this.deviceRepo.getAllActiveDevices()

    let modifiedCount = 0
    let deletedCount = 0

    for (const device of activeDevices) {
      const monitorRecord = await this.appMonitorUserRepo.findActiveByDeviceId(device.deviceId)

      if (monitorRecord && monitorRecord.lastActiveAt !== null) {
        const isInactiveTooLong = AppDayjs(monitorRecord.lastActiveAt).isBefore(thresholdTime)

        if (isInactiveTooLong) {
          modifiedCount++
          await this.deviceSharedService.updateDeviceActive(device.deviceId, false)
        }
      }
      else {
        // no last active at, this means this device may been generated by api but not real browser activity
        // delete non-monitor user device
        const res = await this.deviceRepo.deleteNonMonitorUserDevice(device.deviceId)
        // also delete monitor record
        await this.appMonitorUserRepo.delMonitorByDeviceId(device.deviceId)

        if (res)
          deletedCount++
      }
    }

    return {
      matchedCount: activeDevices.length,
      modifiedCount,
      deletedCount,
    }
  }
}
