/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "business": {
        "system": {
            "locale": {
                "updateExist": string;
            };
            "delete": {
                "recoverFail": string;
            };
        };
        "auth": {
            "sendVerifyCodeError": string;
            "verifyCodeError": string;
        };
    };
    "email": {
        "welcome": {
            "subject": string;
            "title": string;
            "desc1": string;
            "desc2": string;
            "here": string;
        };
        "verify": {
            "subject": string;
            "title": string;
            "desc1": string;
            "desc2": string;
            "desc3": string;
        };
    };
    "index": {
        "hello": string;
        "hello.user": string;
    };
    "response": {
        "20000": string;
        "40000": string;
        "40001": string;
        "40002": string;
        "40003": string;
        "40004": string;
        "40100": string;
        "40101": string;
        "40102": string;
        "40103": string;
        "40104": string;
        "40105": string;
        "40106": string;
        "40107": string;
        "40108": string;
        "40109": string;
        "40110": string;
        "40111": string;
        "40300": string;
        "40400": string;
        "40401": string;
        "40600": string;
        "40601": string;
        "40602": string;
        "40603": string;
        "40604": string;
        "40605": string;
        "40800": string;
        "42900": string;
        "50000": string;
        "50001": string;
        "50300": string;
        "50301": string;
        "50400": string;
        "50500": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
