export const WalnutAdminConstDecoratorEncryptMetadataKey = {
  RES_ENCRYPT:
    'WALNUT_ADMIN_CONST_DECORATOR_METADATAKEY_RES_ENCRYPT',
  REQ_DECRYPT:
    'WALNUT_ADMIN_CONST_DECORATOR_METADATAKEY_REQ_DECRYPT',
} as const
