// app auth strategy
export const WalnutAdminConstAppAuthStrategy = {
  JWT_LOCAL_EMAIL: 'WALNUT_ADMIN_JWT_LOCAL_EMAIL',
  JWT_LOCAL_PHONE: 'WALNUT_ADMIN_JWT_LOCAL_PHONE',
  JWT_ACCESS_TOKEN: 'WALNUT_ADMIN_JWT_ACCESS_TOKEN',
  JWT_REFRESH_TOKEN: 'WALNUT_ADMIN_JWT_REFRESH_TOKEN',

  AUTH_OPAQUE: 'WALNUT_ADMIN_AUTH_OPAQUE',

  OAUTH_GITHUB: 'WALNUT_ADMIN_OAUTH_GITHUB',
  OAUTH_GITEE: 'WALNUT_ADMIN_OAUTH_GITEE',
  OAUTH_GOOGLE_FED_CM: 'WALNUT_ADMIN_OAUTH_GOOGLE_FED_CM',
} as const
