services:
  prod-mongodb-primary:
    image: docker.io/bitnami/mongodb:latest
    restart: always
    container_name: prod-mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=30PatL3c2GqeUkVc76vRc9VFW5b34tnk
      - MONGODB_REPLICA_SET_KEY=WalnutAdminNestjsMongoDBReplicasetProdName
      - MONGODB_REPLICA_SET_NAME=WalnutAdminNestjsMongoDBReplicasetProdName
      - MONGODB_ADVERTISED_HOSTNAME=prod-mongodb-primary
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - 27017:27017

  prod-mongodb-secondary:
    image: docker.io/bitnami/mongodb:latest
    restart: always
    container_name: prod-mongodb-secondary
    depends_on:
      - prod-mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=prod-mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_USER=root
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=30PatL3c2GqeUkVc76vRc9VFW5b34tnk
      - MONGODB_REPLICA_SET_KEY=WalnutAdminNestjsMongoDBReplicasetProdName
      - MONGODB_REPLICA_SET_NAME=WalnutAdminNestjsMongoDBReplicasetProdName
      - MONGODB_ADVERTISED_HOSTNAME=prod-mongodb-secondary
    ports:
      - 27027:27017

  prod-mongodb-arbiter:
    image: docker.io/bitnami/mongodb:latest
    restart: always
    container_name: prod-mongodb-arbiter
    depends_on:
      - prod-mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=prod-mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_USER=root
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=30PatL3c2GqeUkVc76vRc9VFW5b34tnk
      - MONGODB_REPLICA_SET_KEY=WalnutAdminNestjsMongoDBReplicasetProdName
      - MONGODB_REPLICA_SET_NAME=WalnutAdminNestjsMongoDBReplicasetProdName
      - MONGODB_ADVERTISED_HOSTNAME=prod-mongodb-arbiter
    ports:
      - 27037:27017

  redis:
    restart: always
    container_name: prod-single-redis
    image: docker.io/bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=9mFNGHGgIts3ZtspjVLui2ThEXOycB31
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  mongodb_master_data:
    driver: local
  redis_data:
    driver: local