import { Injectable, Logger } from '@nestjs/common'
import { registerAfterCommitHook, WalnutDBInjectModel, WalnutDBModelName } from '@walnut-server/db'
import { WalnutAdminExceptionDataNotFound } from '@walnut-server/exceptions/base/404'
import { WalnutAdminExceptionDeviceNotAcceptable } from '@walnut-server/exceptions/base/406'
import { AppDayjs } from '@walnut-server/utils/dayjs'

import { omit } from 'lodash'
import { ClientSession } from 'mongoose'
import { DeviceTypeConst, IDeviceTypeConst } from '@/common/dto/shared.dto'
import { AppMonitorUserRepositoryService } from '@/modules/app/monitor/user/repo/user.repo.service'
import { SharedIpService } from '@/modules/shared/ip/ip.service'
import { AppTechCacheDeviceService } from '@/modules/techniques/cache/service/cache.device'
import { SysUserDeviceSharedService } from '../user_device/shared/user_device.shared.service'
import { SysDeviceBasicRepository } from './device.basic.repository'
import { SysDeviceDTOInitialRequest, SysDeviceDTOListRequest } from './dto/device.dto'
import { SysDeviceRepositoryService } from './repo/device.repo.service'
import { ISysDeviceDocument, ISysDeviceModel } from './schema/device.schema'

const botPattern = /bot|crawl|slurp|spider/i
const tabletPattern = /Tablet|iPad/i
const mobilePattern = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i

@Injectable()
export class SysDeviceService {
  private readonly logger = new Logger(SysDeviceService.name)

  constructor(
    @WalnutDBInjectModel(WalnutDBModelName.SYS_DEVICE)
    private readonly DeviceModel: ISysDeviceModel,

    private readonly cacheDeviceService: AppTechCacheDeviceService,

    private readonly deviceBasicRepo: SysDeviceBasicRepository,
    private readonly appMonitorUserRepoService: AppMonitorUserRepositoryService,
    private readonly userDeviceSharedService: SysUserDeviceSharedService,
    private readonly deviceRepoService: SysDeviceRepositoryService,
    private readonly sharedIpService: SharedIpService,
  ) { }

  /**
   * @description get device id from request, generated by doubao
   */
  private getDeviceTypeByUA(userAgent: string, screenWidth: number): IDeviceTypeConst {
    if (botPattern.test(userAgent)) {
      return DeviceTypeConst.BOT
    }

    if (tabletPattern.test(userAgent)) {
      return DeviceTypeConst.TABLET
    }

    if (mobilePattern.test(userAgent)) {
      return DeviceTypeConst.MOBILE
    }

    if (screenWidth < 768) {
      return DeviceTypeConst.MOBILE
    }
    else if (screenWidth >= 768 && screenWidth < 1024) {
      return DeviceTypeConst.TABLET
    }

    return DeviceTypeConst.DESKTOP
  }

  /**
   * @description initial device - optimized version
   */
  async initial(req: IWalnutAdminExpressRequest, payload: SysDeviceDTOInitialRequest, dbSession: ClientSession) {
    try {
      const deviceId = this.deviceRepoService.getDeviceIdByFingerprint(req.fingerprint)
      const locationInfo = await this.sharedIpService.getLocationInfoFromFreeAPI(req.realIp)

      const deviceData: Partial<ISysDeviceDocument> = {
        deviceName: payload.deviceName,
        private: payload.private,
        deviceId,
        sr: payload.sr,
        vp: payload.vp,
        deviceInfo: {
          ...payload.deviceInfo,
          os: req.os,
          browser: req.browser,
          type: this.getDeviceTypeByUA(req.userAgent?.ua as string, payload.sr.height),
        },
        hardwareInfo: payload.hardwareInfo,
        geoLocation: {
          type: 'Point',
          coordinates: [locationInfo.longitude!, locationInfo.latitude!],
        },
        locationInfo: {
          country: locationInfo.country,
          region: locationInfo.region,
          city: locationInfo.city,
        },
        locationHistory: [
          {
            ip: req.realIp,
            location: {
              country: locationInfo.country,
              region: locationInfo.region,
              city: locationInfo.city,
            },
            timestamp: AppDayjs().valueOf(),
          },
        ],
        ipHistory: [req.realIp],
        ip: req.realIp,
        active: true,
      }

      // 使用 upsert 一次性完成创建或更新
      const result = await this.DeviceModel.findOneAndUpdate(
        { deviceId },
        { $set: deviceData },
        {
          upsert: true,
          returnDocument: 'after',
          session: dbSession,
          setDefaultsOnInsert: true,
        },
      ).lean()

      registerAfterCommitHook(async () => {
        await this.cacheDeviceService.setSysDeviceCache(result)
      })

      return {
        deviceId: result.deviceId,
        locationInfo,
      }
    }
    catch (err) {
      this.logger.error(err)
      throw new WalnutAdminExceptionDeviceNotAcceptable()
    }
  }

  /**
   * @description read device by id
   */
  async read(id: string) {
    const read = await this.DeviceModel.findById(id)

    if (!read) {
      throw new WalnutAdminExceptionDataNotFound()
    }

    return read
  }

  /**
   * @description list
   */
  async list(params: SysDeviceDTOListRequest) {
    const location = params.query.location ?? null

    const cleanParams = omit(params, ['query.location']) as SysDeviceDTOListRequest

    if (location === null)
      return this.deviceBasicRepo.list(cleanParams)

    return this.deviceBasicRepo.list(cleanParams, [
      {
        $match: {
          $expr: {
            $or: [
              { $regexMatch: { input: '$locationInfo.country', regex: location, options: 'i' } },
              { $regexMatch: { input: '$locationInfo.region', regex: location, options: 'i' } },
              { $regexMatch: { input: '$locationInfo.city', regex: location, options: 'i' } },
            ],
          },
        },
      },
    ])
  }

  /**
   * @description get current active user by device id
   */
  async getCurrentActiveUser(id: string) {
    const target = await this.DeviceModel.findById(id)
    if (!target) {
      throw new WalnutAdminExceptionDataNotFound()
    }
    return this.appMonitorUserRepoService.findActiveUserByDeviceId(target.deviceId)
  }

  /**
   * @description get history users by device id
   */
  async getHistoryUsersByDeviceId(id: string) {
    const target = await this.DeviceModel.findById(id)
    if (!target) {
      throw new WalnutAdminExceptionDataNotFound()
    }
    return this.userDeviceSharedService.getAllUsersByDeviceId(target.deviceId)
  }

  /**
   * @description lock device by id
   */
  async lock(id: string) {
    const target = await this.DeviceModel.findById(id)
    if (!target) {
      throw new WalnutAdminExceptionDataNotFound()
    }
    target.locked = true
    await this.cacheDeviceService.setSysDeviceCache(target)
    return true
  }

  /**
   * @description unlock device by id
   */
  async unlock(id: string) {
    const target = await this.DeviceModel.findById(id)
    if (!target) {
      throw new WalnutAdminExceptionDataNotFound()
    }
    target.locked = false
    await this.cacheDeviceService.setSysDeviceCache(target)
    return true
  }

  /**
   * @description ban device by id
   */
  async ban(id: string) {
    const target = await this.DeviceModel.findById(id)
    if (!target) {
      throw new WalnutAdminExceptionDataNotFound()
    }
    target.banned = true
    await this.cacheDeviceService.setSysDeviceCache(target)
    return true
  }

  /**
   * @description unban device by id
   */
  async unban(id: string) {
    const target = await this.DeviceModel.findById(id)
    if (!target) {
      throw new WalnutAdminExceptionDataNotFound()
    }
    target.banned = false
    await this.cacheDeviceService.setSysDeviceCache(target)
    return true
  }
}
